# Maintainer: reekta92 <mdag.92988@protonmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=graf-bin
pkgver=0.4.11
pkgrel=1
pkgdesc="Terminal-based force-directed graph visualizer for markdown wikilinks"
url="https://github.com/reekta92/graf"
license=("GPL-3.0-only")
arch=("x86_64")
provides=("graf")
conflicts=("graf")
source=("https://github.com/reekta92/graf/releases/download/v$pkgver/graf-$pkgver-x86_64.tar.gz")
sha256sums=("54e14ce16d6885a73cd3c71e3e19e2d2aa01fc3e90788be10fd6129feb746a16")

package() {
    install -Dm755 graf -t "$pkgdir/usr/bin"
}
