# Maintainer: reekta92 <mdag.92988@protonmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=graf-rs-bin
pkgver=0.4.14
pkgrel=1
pkgdesc="Terminal-based force-directed graph visualizer for markdown wikilinks"
url="https://github.com/reekta92/graf"
license=("GPL-3.0-only")
arch=("x86_64")
provides=("graf-rs")
conflicts=("graf-rs")
source=("https://github.com/reekta92/graf/releases/download/v$pkgver/graf-rs-$pkgver-x86_64.tar.gz")
sha256sums=("3bdb8151d59702e85cdde3a2233e1788a442d53fd0b93aaf9d615306abaf90a4")

package() {
    install -Dm755 graf -t "$pkgdir/usr/bin"
}
